var MSG = {
  title: "Codice",
  blocks: "Blocchi",
  linkTooltip: "Salva e collega ai blocchi.",
  runTooltip: "Esegui il programma definito dai blocchi nell'area di lavoro.",
  badCode: "Errore programma:\n%1",
  timeout: "È stato superato il numero massimo consentito di interazioni eseguite.",
  trashTooltip: "Elimina tutti i blocchi.",
  catLogic: "Logica",
  catLoops: "Cicli",
  catMath: "Matematica",
  catText: "Testo",
  
  catLists: "Elenchi",
  catColour: "Colore",
  catVariables: "Variabili",
  catFunctions: "Funzioni",
  listVariable: "elenco",
  textVariable: "testo",
  httpRequestError: "La richiesta non è stata soddisfatta.",
  linkAlert: "Condividi i tuoi blocchi con questo collegamento:\n\n%1",
  hashError: "Mi spiace, '%1' non corrisponde ad alcun programma salvato.",
  xmlError: "Non è stato possibile caricare il documento.  Forse è stato creato con una versione diversa di Blockly?",
  badXml: "Errore durante l'analisi XML:\n%1\n\nSeleziona 'OK' per abbandonare le modifiche o 'Annulla' per continuare a modificare l'XML.",

/**Toolbox begin*/
 /** toolbox的开始 */
  id_start: "Avvia",
  id_actions: "Mosse",
  id_moves : "Mosse",
  id_sensors : "Sensori",
  id_events : "Eventi",
  id_math : "Mate",
  id_control : "Controllo",
  id_show : "Mostra",
/**Toolbox end*/
/**Start Category begin */
  id_when_start : "Fai clic su \"Esegui\" per iniziare",
  id_go_to_start : "Vai a Start",
/**Start Category end */
 
/**Sensor Category */
  id_sensor_IR_sensor: 'Sensore IR',
  id_sensor_reflectance_between_obstacle:'reflectance_between_obstacle',
  id_sensor_touch_sensor:'Sensore a sfioramento',
  id_sensor_touch_sensor_status:'stato',
  id_sensor_gyroscope:'Giroscopio',
  id_sensor_angle:'angolo',
  y_axie:'Angolo di rollio',
  x_axie:'Angolo di inclinazione',
  z_axie:'Angolo girodirezionale',
  servo:'Servomotore',
  id_sensor_set_gyroscope:'Imposta giroscopio',
  id_sensor_angle_to_zero:'angolo a 0',
  id_math_variables_set_add : "%1 + %2",
  id_set : "imposta",
  id_to : "su",
  id_control_wait_for : 'attendi',
  id_control_repeat : 'ripeti',
  id_control_repeat_times: 'volte',
  id_control_wait:'attendi',
  id_control_seconds:'ms',
  id_math_not:'non',

  /* common section begin */
  btn_name_confirm : "ok",
  btn_name_cancel: "annulla",
  /* common section end*/

  /*event component section begin*/
  maincontrol_box :"Scatola di comando principale",
  low_power :"Basso consumo",
  ir_sensor : "Sensore IR",
  reflectance : "riflettività",
  touch_sensor:"Sensore a sfioramento",
  status : "lo stato è",
  title_touch_sensor : "Impostazione sensore a sfioramento",
  click : "Fai clic",
  db_click : "Fai doppio clic",
  press_hold : "Premi Sospendi",
  release : "Rilascia",
  gyroscope : "Giroscopio",
  angle : "angolo",
  axie : 'asse',
  title_device_tilt : "Impostazione stato telefono/pad",
  phone_pad :"Telefono/Pad",
  tilt_left : "Inclina a sinistra",
  tilt_right : "Inclina a destra",
  tilt_up : "Inclina verso l'alto",
  tilt_down : "Inclina verso il basso",
  tilt_swing : "Inclina per oscillare",
  /*event component section end*/

  /** control  */
  id_while : 'durante',
  id_until : 'fino a',
  id_repeat : 'fai',
  id_start_info : 'Esegui',
  id_stop_info : 'Arresta',
  title_infrared_sensor : "Impostazione sensore a infrarossi",
  current_value : 'valore corrente',
  distance_1: 'troppo vicino',
  distance_2:'vicino',
  distance_3:'intermedio',
  distance_4:'lontano',
  distance_5:'troppo lontano',

  /* need to be removed, wait to confirm */
  distance_very_near: 'troppo vicino',
  distance_near:'vicino',
  distance_middle:'intermedio',
  distance_far:'lontano',
  distance_very_far:'troppo lontano',
  id_servo : 'servomotore',
  id_rotate : 'ruota',
  id_degree : 'grado',
  id_in : 'durante',
  id_millsecond : 'ms',
  id_rotate_circle : 'Ruota il servomotore di 360°',
  id_servos : 'Servomotori',
  id_run_to : 'esegui su',

  /* display section begin */
  title_setting_light : "Impostazione indicatore",
  title_setting_tune : "Impostazione melodia",
  title_setting_emotion : "Impostazione emozione",
  id_all_bright: "tutto luminoso",
  id_custom: "personalizza",
  id_smile: 'sorridente',
  id_cry : 'che piange',
  id_sad : 'triste',
  id_wink : 'che fa l\'occhiolino',
  id_dizzy : 'frastornato',
  id_daze : 'sbalordito',
  id_open_eyes : 'occhi aperti',
  id_close_eyes : 'occhi chiusi',
  /* display section end */

  id_all: 'Tutto',
  id_lock : 'blocca',
  id_unlock : 'sblocca',
  title_bluetooth_connect : "Connessione Bluetooth",
  title_time_adjust : "Regolazione ora",
  // Show
  id_show_play_effect:'Riproduci effetto',
  id_show_play_tune:'Riproduci melodia',
  id_show_show_emoji:'Visualizza emoji',
  id_show_show_LEDs:'Visualizza LED',
  id_show_time_during:'per',
  id_show_time_ms:'ms',
  id_show_times:'volte',
    /*展示  begin*/
  sound_effects_popup_title :"Imposta effetti audio",
  sound_effects_popup_cancel :"Annulla",
  sound_effects_popup_ok :"OK",
  sound_effects_recording_add :"Aggiungi nuova registrazione",
  sound_effects_recording_delete :"Elimina",
  servo_id : 'ID',
  servo_angle : 'Angolo',
  movement_gesture: 'Posizione', 
  servo_direction : 'direzione',
  servo_speed : 'velocità',
  /*展示  end*/
  /*运动  begin*/
  servo_angle_popup_title :"Imposta angolo di rotazione per il servomotore",
  servo_angle_popup_close:"Chiudi",
  servo_angle_popup_variable:"Variabile",
  servo_angle_popup_angle:"Angolo",
  servo_angle_popup_cancel :"Annulla",
  servo_angle_popup_ok :"OK",
  rotate_servo_popup_clockwise:"Senso orario",
  rotate_servo_popup_anti_clockwise:"Senso antiorario",
  rotate_servo_popup_stop:"arresta",
  rotate_servo_popup_title:"Modalità di rotazione",
  rotate_servo_popup_cancel:"Annulla",
  rotate_servo_popup_ok:"OK",
  servo_status_popup_title:"Imposta stato del servomotore",
  servo_status_popup_cancel:"Annulla",
  servo_status_popup_ok:"OK",
  servo_status_popup_locking:"Blocca",
  servo_status_popup_adjustable:"Sblocca",
  servo_status_popup_tips:"Impossibile regolare il servomotore corrispondente per il robot quando in modalità bloccata",
  posture_named_popup_title :"Denomina la posizione",
  posture_named_popup_cancel :"Annulla",
  posture_named_popup_ok :"OK",
  posture_named_popup_placeholder :"Posizione",
  posture_named_popup_msg :"Il nome della posizione contiene caratteri non validi",
  posture_named_too_long : "Il nome della posizione non può superare i %1 caratteri",
  gyro_rotate_direction_popup_title :"Seleziona la direzione di rotazione per il servomotore",
  gyro_rotate_direction_popup_cancel :"Annulla",
  gyro_rotate_direction_popup_ok :"OK",
  gyro_rotate_direction_popup_curVal :"Valore corrente",
  gyro_rotate_direction_popup_course :"Angolo girodirezionale",
  gyro_rotate_direction_popup_horizontal :"Angolo di rollio",
  gyro_rotate_direction_popup_house :"Angolo di inclinazione",
/*运动  end*/
  
  index_back:"Indietro",
  disconnected : "Scollegato",

  /*项目  begin*/
  //保存项目
  add_project_placeholder : "Nuovo progetto",
  project_pop_ok_btn: "OK",
  project_pop_cancel_btn: "Annulla",
  add_project_pop_title : "Nome progetto",
  add_project_input_check : "Può contenere solo 16 caratteri",
  project_name_too_long : "Il nome del progetto non può superare i %1 caratteri",
  project_name_popup_msg : "Il nome del progetto contiene caratteri non validi",
  //是否保存项目
  is_add_project_pop_title :"Salva progetto",
  is_add_project_pop_tips :"Salvare il progetto corrente?",
  //项目列表
  project_list_title :"I miei progetti",
  porject_alert_title:"Errore",
  porject_alert_tips:"Suggerimenti",
  porject_alert_content:"Parametro errato per il target operativo. Verifica.",
  porject_alert_content_01:"Nome elemento già esistente. Inseriscilo di nuovo.",
  porject_alert_content_02:"Errore nel funzionamento del servizio di base. Il messaggio di errore è:",
  porject_alert_content_03:"Errore nei dati ricevuti dalla base.",
  porject_alert_content_04:"Impossibile leggere il progetto ",
  porject_alert_content_05:"Il blocco programma nel file del progetto contiene errori.",
  porject_alert_content_06:"Progetto salvato",
  porject_alert_btnText:"OK",
  add_recording_ok:"OK",
  recording_tips:"Registrazione",
  id_control_break : 'Fuori circolazione',
  id_blue_disconnect : 'Bluetooth non connesso',
  id_ok : 'OK',
  recording_title:"Registrazione",
  recording_cancel:"Annulla",
  recording_ok:"OK",
  recording_placeholder:"Inserisci un nome di registrazione",
  recording_popup_title:"Input nome file registrato",
  /*项目  end*/
  
/*设置音效弹出框音效文件国际化  begin*/
  animal:"animale",
  machine:"macchina",
  recording:"registrazione",
  bear:"orso",
  bird:"uccello",
  chicken:"gallina",
  cow:"mucca",
  dog:"cane",
  elephant:"elefante",
  giraffe:"giraffa",
  horse:"cavallo",
  lion:"leone",
  monkey:"scimmia",
  pig:"maiale",
  rhinoceros:"rinoceronte",
  sealions:"leoni marini",
  tiger:"tigre",
  walrus:"tricheco",
  ambulance:"ambulanza",
  busy_tone:"busy_tone",
  carhorn:"clacson",
  carhorn1:"clacson 1",
  doorbell:"campanello",
  engine:"motore",
  laser:"laser",
  meebot:"meebot",
  police_car_1:"police_car_1",
  police_car_2:"police_car_2",
  ringtones:"suonerie",
  robot:"robot",
  telephone_call:"telephone_call",
  touch_tone:"touch_tone",
  wave:"onda",
/*设置音效弹出框音效文件国际化  end*/

  variable_named_popup_placeholder :"Variabile",
  title_variable_set : 'Imposta variabile',
  variable_named_popup_msg :"il nome della variabile contiene caratteri non validi",
  variable_named_too_long : "il nome della variabile non può superare i %1 caratteri",
  speed:"velocità",
  speed_VS:"molto lento",
  speed_S:"lento",
  speed_M:"intermedio",
  speed_V:"veloce",
  speed_VF:"molto veloce",
  speed_no_value:"Sterzo senza ruota dell'attrezzatura corrente",
  speed_only_360_value:"L'attrezzatura corrente non dispone di uno sterzo senza ruota a 360°",
  lights_tips:"Il modello attuale non è collegato ad alcuna luce",
  exit_tips:"Il programma corrente non è stato salvato. Uscire?",
  project_has_no_change:"Il programma corrente non ha subito modifiche",
  close_blue:"Il Bluetooth è connesso. Si disconnette?",
  posture_link:"Il modello non è connesso. Connettere prima il modello",
  posture_link_popup_title:"Il modello si connette",
  posture_link_popup_cancel:"annulla",
  posture_link_popup_ok:"ok",
  recording_name_repeat:"Nome registrato ripetuto",
  recording_named_too_long : "Il nome è troppo lungo. Inserirlo nuovamente.",
  recording_alert_title:"Errore",
  recording_alert_content:"concessione privilegiata non riuscita",
  recording_alert_ok:"OK",
  help_title:"Blocca introduzione",
  newProjectName:"Nuovo progetto",
  sysVoiceName:"voce",
  exit_popup_cancel:"Annulla",
  exit_popup_ok:"OK",
  exit_popup_title:"Suggerimenti",
  recording_data_tips:"Il sistema corrente non dispone di file di registrazione personalizzati.",


  //未录入部分
  movements:"movements",
  posture_set_desc : "Aprire l'interruttore a destra e impostare l'azione del robot",
  posture_ok_desc : "Pose dopo l'immissione nome posizione",
  input_rule_msg : "Impossibile inserire caratteri speciali. È possibile inserire un massimo di %1 caratteri o %2 caratteri cinesi.",
  variable_inputrule_msg : "Impossibile iniziare con una cifra. Impossibile inserire caratteri speciali. È possibile inserire un massimo di %1 caratteri o %2 caratteri cinesi.",
  recording_name_popup_msg : "Nome registrazione contiene caratteri non validi",
  infrared_tips:"sensore a infrarossi non è collegata al modello attuale",
  touch_tips:"Il sensore touch non è collegato al modello attuale",
  gyroscope_tips:"Il sensore di rotazione non è collegata al modello attuale",
  id_infinite_loop_error:'uscire dal programma a causa di esaurimento della memoria, si prega di tornare indietro e riprovare',
  // 新手指引
  save_project_msg:"Tocca qui per salvare il tuo programma!",
  projectlist_msg:"Visualizza i programmi che Jimu ha imparato e in cui è ormai un esperto e crea nuovi programmi per lui!",
  swift_msg:"Tocca qui per visualizzare il codice SWIFT!",
  help_msg:"Tocca qui se hai ulteriori domande!",
  run_msg:"Fai muovere Jimu in base alla tua programmazione!",
  go_skip:"Ignora",
  servo_mode_error : 'Errore modalità servomotore',
  set_servo_mode : 'Impostazioni',
  id_show_scenelight:'Visualizza indicatore LED',
  title_setting_scenelight : "Configura indicatore LED",
  id_happy:"Felice",
  id_jingya:"Sorpreso",    
  id_relei:"Lacrime",
  id_leiguang:"Lacrime luminose",
  id_shangxin:"Triste",
  id_yun:"Frastornato",
  id_fadai:"Sbalordito",
  id_zhayan:"Occhiolino",
  id_haixiu:"Timido",
  id_shanshuo:"Scintilla",
  id_huxi:"Respiro",
  id_fengshan:"Ventilatore",
  id_yugua:"Tergicristalli",

  id_deng:"7 indicatori colorati",
  id_disco:"Disco",
  id_caise:"Impilamento colori",
  id_sanyuanse:"Colori primari",
  select_all:"Tutto",
  no_common_servo_info : "Nessuna modalità di angolazione del servomotore attualmente disponibile (è possibile effettuare una rotazione entro un intervallo designato). Configurarne una?",
  no_circle_servo_info : "Nessuna modalità ruota del servomotore attualmente disponibile (è possibile effettuare una rotazione di 360°). Configurarne una?",
  touch_tips_error : 'La corrente ID blocco non è corretto, si prega di eliminarlo e ripristinare',

  shumaguan:"Digital Tube",
  show_time:"Show time",
  show_number:"Show number",
  show_count:"Show timer",
  stop_count:"Stop timer",
  show_countdown:"Show countdown",
  set_countdown:"Countdown setting",
  let_show_number:"Show number with nixie tube",
  let_show_time:"Show time with nixie tube",
  let_show_count:"Show timer with nixie tube",
  let_stop_count:"Stop timer with nixie tube",
  let_show_countdown:"Show countdown with nixie tube",
  let_led_scenelight:"Show scene lighting with LED lights",
  long_lighton:"Always on",
  no_project_tip:"Nessun progetto, fai clic su + in alto a destra per crearne uno."

};
