var MSG = {
  title: "코드",
  blocks: "블록",
  linkTooltip: "블록을 저장하고 링크를 가져옵니다.",
  runTooltip: "작업 공간에서 블록으로 정의된 프로그램을 실행합니다.",
  badCode: "프로그램 오류:\n%1",
  timeout: "최대 실행 반복을 초과했습니다.",
  trashTooltip: "모든 블록을 버립니다.",
  catLogic: "논리",
  catLoops: "반복",
  catMath: "수학",
  catText: "텍스트",
  catLists: "목록",
  catColour: "색",
  catVariables: "변수",
  catFunctions: "기능",
  listVariable: "목록",
  textVariable: "텍스트",
  httpRequestError: "요청에 문제가 있습니다.",
  linkAlert: "다음 링크로 블록을 공유하세요:\n\n%1",
  hashError: "죄송하지만 '%1'은 어떤 저장된 프로그램으로 일치하지 않습니다.",
  xmlError: "저장된 파일을 불러올 수 없습니다. 혹시 블록리의 다른 버전으로 만들었습니까?",
  badXml: "XML 구문 분석 오류:\n%1\n\n바뀜을 포기하려면 '확인'을 선택하고 XML을 더 편집하려면 '취소'를 선택하세요.",

  /**Toolbox */
  id_start: "시작",
  id_actions: "이동",
  id_moves : "이동",
  id_sensors : "센서",
  id_events : "이벤트",
  id_math : "수학",
  id_control : "제어",
  id_show : "표시",

/**Begin Category */
  id_when_start : "‘실행’을 클릭하여 시작",
  id_go_to_start : "시작으로 이동",

/**Sensor Category */
  id_sensor_IR_sensor: 'IR 센서',
  id_sensor_reflectance_between_obstacle:'장애물_간_반사율',
  id_sensor_touch_sensor:'터치 센서',
  id_sensor_touch_sensor_status:'상태',
  id_sensor_gyroscope:'자이로스코프',
  id_sensor_angle:'각도',
  y_axie:'롤 각도',
  x_axie:'피치 각도',
  z_axie:'헤딩 각도',
  servo:'서보',
  id_sensor_set_gyroscope:'자이로스코프 설정',
  id_sensor_angle_to_zero:'각도 0',

  id_math_variables_set_add : "%1 + %2",
  id_set : "설정",
  id_to : "대상",

  id_control_wait_for : '대기',
  id_control_repeat : '반복',
  id_control_repeat_times: '회',
  id_control_wait:'대기',
  id_control_seconds:'ms',
  id_math_not:'not',

  /* common section begin */
  btn_name_confirm : "확인",
  btn_name_cancel: "취소",

  /* common section end*/

  /*event component section begin*/
  maincontrol_box :"메인컨트롤 박스",
  low_power :"저전력",
  ir_sensor : "IR 센서",
  reflectance : "반사율",
  touch_sensor:"터치 센서",
  status : "상태는",
  title_touch_sensor : "터치 센서 설정",
  click : "클릭",
  db_click : "더블 클릭",
  press_hold : "홀드 누르기",
  release : "해제",
  gyroscope : "자이로스코프",
  angle : "각도",
  axie : '액슬',
  title_device_tilt : "전화기/패드 상태 설정",
  phone_pad :"전화기/패드",
  tilt_left : "왼쪽 기울이기",
  tilt_right : "오른쪽 기울이기",
  tilt_up : "위로 기울이기",
  tilt_down : "아래로 기울이기",
  tilt_swing : "기울여 돌리기",
  /*event component section end*/

  /** control  */
  id_while : '동안',
  id_until : '까지',
  id_repeat : '수행',

  id_start_info : '실행',
  id_stop_info : '정지',

  title_infrared_sensor : "적외선 센서 설정",
  current_value : '현재 값',
  distance_1: '너무 가까움',
  distance_2:'가까움',
  distance_3:'중간',
  distance_4:'멈',
  distance_5:'너무 멈',

  /* need to be removed, wait to confirm */
  distance_very_near: '너무 가까움',
  distance_near:'가까움',
  distance_middle:'중간',
  distance_far:'멈',
  distance_very_far:'너무 멈',

  id_servo : '서보',
  id_rotate : '회전',
  id_degree : '도',
  id_in : '동안',
  id_millsecond : 'ms',

  id_rotate_circle : '서보 360° 회전',
  id_servos : '서보',
  id_run_to : '실행',

  /* display section begin */
  title_setting_light : "조명 설정",
  title_setting_tune : "튠 설정",
  title_setting_emotion : "감정 설정",
  id_all_bright: "모두 밝음",
  id_custom: "사용자 정의",
  id_smile: '미소',
  id_cry : '울음',
  id_sad : '슬픔',
  id_wink : '윙크',
  id_dizzy : '어지러움',
  id_daze : '현혹',
  id_open_eyes : '눈 뜨기',
  id_close_eyes : '눈 감기',
  /* display section end */

  id_all: '전체',
  id_lock : '잠금',
  id_unlock : '잠금 해제',

  title_bluetooth_connect : "Bluetooth 연결",
  title_time_adjust : "시간 조정",

  // Show
  id_show_play_effect:'플레이 효과',
  id_show_play_tune:'플레이 튠',
  id_show_show_emoji:'이모티콘 표시',
  id_show_show_LEDs:'LED 표시',
  id_show_time_during:'동안',
  id_show_time_ms:'ms',
  id_show_times:'회',
    /*展示  begin*/
  sound_effects_popup_title :"음향 효과 설정",
  sound_effects_popup_cancel :"취소",
  sound_effects_popup_ok :"확인",
  sound_effects_recording_add :"새 기록 추가",
  sound_effects_recording_delete :"삭제",

  servo_id : 'ID',
  servo_angle : '각도',
  movement_gesture: '자세', 
  servo_direction : '방향',
  servo_speed : '속도',

    /*展示  end*/

    /*运动  begin*/
  servo_angle_popup_title :"서보 모터 회전 각도 설정",
  servo_angle_popup_close:"닫기",
  servo_angle_popup_variable:"변수",
  servo_angle_popup_angle:"각도",
  servo_angle_popup_cancel :"취소",
  servo_angle_popup_ok :"확인",

  rotate_servo_popup_clockwise:"시계 방향",
  rotate_servo_popup_anti_clockwise:"반시계 방향",
  rotate_servo_popup_stop:"정지",
  rotate_servo_popup_title:"회전 모드",
  rotate_servo_popup_cancel:"취소",
  rotate_servo_popup_ok:"확인",

  servo_status_popup_title:"서보 모터 상태 설정",
  servo_status_popup_cancel:"취소",
  servo_status_popup_ok:"확인",
  servo_status_popup_locking:"잠금",
  servo_status_popup_adjustable:"잠금 해제",
  servo_status_popup_tips:"잠금 모드에서는 로봇의 해당 서보를 조정할 수 없습니다.",

    posture_named_popup_title :"자세 이름 지정",
    posture_named_popup_cancel :"취소",
    posture_named_popup_ok :"확인",
    posture_named_popup_placeholder :"자세",
    posture_named_popup_msg :"자세 이름에 규칙에 어긋난 글자가 포함되어 있습니다.",
    posture_named_too_long : "자세 이름은 %1 글자를 넘을 수 없습니다.",

    gyro_rotate_direction_popup_title :"서보 모터의 회전 방향 선택",
    gyro_rotate_direction_popup_cancel :"취소",
    gyro_rotate_direction_popup_ok :"확인",
    gyro_rotate_direction_popup_curVal :"현재 값",
    gyro_rotate_direction_popup_course :"헤딩 각도",
    gyro_rotate_direction_popup_horizontal :"롤 각도",
    gyro_rotate_direction_popup_house :"피치 각도",


    /*运动  end*/
    index_back:"뒤로",
    disconnected : "연결 해제됨",

    /*项目  begin*/
    //保存项目
    add_project_placeholder : "새 프로젝트",
    project_pop_ok_btn: "확인",
    project_pop_cancel_btn: "취소",
    add_project_pop_title : "프로젝트 이름",
    add_project_input_check : "16 글자만 입력할 수 있습니다.",
    project_name_too_long : "프로젝트 이름은 %1 글자를 초과할 수 없습니다.",
    project_name_popup_msg : "프로젝트 이름에 유효하지 않은 글자가 포함되어 있습니다.",
    //是否保存项目
    is_add_project_pop_title :"프로젝트 저장",
    is_add_project_pop_tips :"현재 프로젝트를 저장하시겠습니까?",
    //项目列表
    project_list_title :"내 프로젝트",
    porject_alert_title:"오류",
    porject_alert_tips:"도움말",
    porject_alert_content:"죄송합니다, 작동 대상에 잘못된 파라미터입니다. 확인해주십시오!",
    porject_alert_content_01:"아이템 이름이 이미 존재합니다. 다시 입력해주십시오.",
    porject_alert_content_02:"베이스 서비스 작업 오류 오류 메시지는 다음과 같습니다.",
    porject_alert_content_03:"베이스에서 수신한 데이터 오류!",
    porject_alert_content_04:"프로젝트 읽기 실패 ",
    porject_alert_content_05:"죄송합니다, 프로젝트 파일의 프로그램 블록에 오류가 있습니다!",
    porject_alert_content_06:"프로젝트 저장됨",
    porject_alert_btnText:"확인",
    /*项目  end*/
    add_recording_ok:"확인",
    recording_tips:"기록",
    id_control_break : '순환 종료',
    id_blue_disconnect : 'Bluetooth가 연결되지 않았습니다',
    id_ok : '확인',
    recording_title:"기록",
    recording_cancel:"취소",
    recording_ok:"확인",
    recording_placeholder:"기록 이름을 입력하십시오",
    recording_popup_title:"기록된 파일 이름 입력",
    /*项目  end*/
    /*设置音效弹出框音效文件国际化  begin*/
    animal:"동물",
    machine:"기계",
    recording:"기록",
    bear:"곰",
    bird:"새",
    chicken:"닭",
    cow:"소",
    dog:"개",
    elephant:"코끼리",
    giraffe:"기린",
    horse:"말",
    lion:"사자",
    monkey:"원숭이",
    pig:"돼지",
    rhinoceros:"코뿔소",
    sealions:"바다사자",
    tiger:"호랑이",
    walrus:"바다코끼리",
    ambulance:"앰뷸런스",
    busy_tone:"busy_tone",
    carhorn:"경적",
    carhorn1:"경적1",
    doorbell:"초인종",
    engine:"엔진",
    laser:"레이저",
    meebot:"미봇",
    police_car_1:"police_car_1",
    police_car_2:"police_car_2",
    ringtones:"벨소리",
    robot:"로봇",
    telephone_call:"telephone_call",
    touch_tone:"touch_tone",
    wave:"웨이브",
    /*设置音效弹出框音效文件国际化  end*/

    variable_named_popup_placeholder :"변수",
    title_variable_set : '변수 설정',
    variable_named_popup_msg :"변수 이름에 규칙에 어긋난 글자가 포함되어 있습니다.",
    variable_named_too_long : "변수 이름은 %1 글자를 초과할 수 없습니다.",
    speed:"속도",
    speed_VS:"매우 느림",
    speed_S:"느림",
    speed_M:"중간",
    speed_V:"빠름",
    speed_VF:"매우 빠름",
    speed_no_value:"현재 장치 휠리스 스티어링",
    speed_only_360_value:"현재 장치에 360 휠리스 스티어링이 없습니다",
    lights_tips:"현재 모델이 조명에 연결되어 있지 않습니다",
    exit_tips:"현재 프로그램이 저장되지 않았습니다, 계속하시겠습니까, 종료하시겠습니까?",
    project_has_no_change:"현재 프로그램이 변경되지 않았습니다.",
    close_blue:"Bluetooth가 연결되었습니까, 분리되었습니까?",
    posture_link:"모델이 연결되지 않았습니다. 모델을 먼저 연결하십시오.",
    posture_link_popup_title:"모델 연결",
    posture_link_popup_cancel:"취소",
    posture_link_popup_ok:"확인",
    recording_name_repeat:"기록된 이름 반복",
    recording_named_too_long : "이름이 너무 깁니다. 다시 입력해주십시오",
    recording_alert_title:"오류",
    recording_alert_content:"권한 부여 실패",
    recording_alert_ok:"확인",
    help_title:"블록 소개",
    newProjectName:"새 프로젝트",
    sysVoiceName:"음성",
    exit_popup_cancel:"취소",
    exit_popup_ok:"확인",
    exit_popup_title:"도움말",
    recording_data_tips:"현재 시스템에 사용자 지정 기록 파일이 없습니다.",
  //需新录入翻译
  movements:"movements",
  posture_set_desc : "오른쪽 스위치를 열고 로봇의 동작을 설정합니다.",
  posture_ok_desc : "입력 위치 이름 뒤 포즈",
  //保存项目
  input_rule_msg : "특수 문자를 입력할 수 없습니다. 최대 %1 문자 또는 %2 중국어 문자를 입력할 수 있습니다.",
  variable_inputrule_msg : "숫자로 시작할 수 없습니다. 특수 문자를 입력할 수 없습니다. 최대 %1 문자 또는 %2 중국어 문자를 입력할 수 있습니다.",
  recording_name_popup_msg : "녹음 이름에 잘못된 문자가 있습니다.",
  infrared_tips:"적외선 센서가 현재 모델에 연결되어 있지 않습니다.",
  touch_tips:"터치 센서가 현재 모델에 연결되어 있지 않습니다.",
  gyroscope_tips:"자이로 센서가 현재 모델에 연결되어 있지 않습니다.",
  id_infinite_loop_error:'메모리 부족으로 프로그램이 종료되었습니다. 다시 돌아가서 다시 시도하십시오.',
  // 新手指引
  save_project_msg:"프로그램을 저장하려면 여기를 탭하십시오!",
  projectlist_msg:"Jimu가 학습하고 마스터한 프로그램을 보고 Jimu를 위한 새 프로그램을 생성합니다!",
  swift_msg:"스위프트 코드를 확인하려면 여기를 탭하십시오!",
  help_msg:"질문이 있다면 여기를 탭하십시오!",
  run_msg:"Jimu를 프로그램한 대로 움직이게 합니다!",
  go_skip:"건너뛰기",
  servo_mode_error : '서보 모드 오류',
  set_servo_mode : '설정',
  id_show_scenelight:'조명 디스플레이 보기',
  title_setting_scenelight : "조명 디스플레이 설정",
  id_happy:"즐거움",
  id_jingya:"놀람",    
  id_relei:"눈물",
  id_leiguang:"반짝이는 눈물",
  id_shangxin:"슬픔",
  id_yun:"어지러움",
  id_fadai:"현혹",
  id_zhayan:"깜박임",
  id_haixiu:"수줍음",
  id_shanshuo:"반짝임",
  id_huxi:"입김",
  id_fengshan:"팬",
  id_yugua:"와이퍼",

  id_deng:"7색 조명",
  id_disco:"Disco",
  id_caise:"컬러 스태킹",
  id_sanyuanse:"기본 색상",
  select_all:"전체",
  no_common_servo_info : "현재 각도 모드 서보(지정된 범위로 회전 가능)가 없습니다. 설정하시겠습니까?",
  no_circle_servo_info : "현재 바퀴 모드 서보(360° 회전 가능)가 없습니다. 설정하시겠습니까?",
  touch_tips_error : '현재 블록 ID가 올바르지 않습니다. 삭제하고 재설정하십시오.',

  shumaguan:"Digital Tube",
  show_time:"Show time",
  show_number:"Show number",
  show_count:"Show timer",
  stop_count:"Stop timer",
  show_countdown:"Show countdown",
  set_countdown:"Countdown setting",
  let_show_number:"Show number with nixie tube",
  let_show_time:"Show time with nixie tube",
  let_show_count:"Show timer with nixie tube",
  let_stop_count:"Stop timer with nixie tube",
  let_show_countdown:"Show countdown with nixie tube",
  let_led_scenelight:"Show scene lighting with LED lights",
  long_lighton:"Always on",
  no_project_tip:"프로젝트가 없습니다. 프로젝트를 생성하려면 오른쪽 상단 코너에서 +를 클릭하십시오."
};
